name: caesar_puzzle
description: Caesarâ€™s Calendar Puzzle

publish_to: 'none'

version: 1.1.1+6

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  get_it: ^9.1.1
  injectable: ^2.7.0
  provider: ^6.1.5+1
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  flutter_platform_widgets: ^9.0.0
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.7
  confetti: ^0.8.0
  package_info_plus: ^9.0.0
  flutter_flip_flap: ^0.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  injectable_generator: ^2.8.1
  build_runner: ^2.7.0
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.11.1
  intl_utils: ^2.8.11
  intl_utils_formatter: ^1.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon.png

  android_12:
    image: assets/splash/splash_icon_light.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

    image_dark: assets/splash/splash_icon_dark.png
    color_dark: "#17111C"
    icon_background_color_dark: "#17111C"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  generate: true

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated

intl_utils_formatter:
  files:
    - lib/l10n/intl_en.arb
    - lib/l10n/intl_uk.arb